spring.application.name=TaskManagementApp
spring.mongodb.uri=mongodb+srv://tomarrishabh02_db_user:eIM2dPcJ9wIdcLR8@cluster0.rwrjzky.mongodb.net/?appName=Cluster0
spring.mongodb.database=taskAppDb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
dog.service.api=https://dogapi.dog/api/v2/breeds/dd9362cc-52e0-462d-b856-fccdcf24b140
jwt.secret.key=mysecretkeymysecretkeymysecretkey